// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {imagemeta} from '../models';

export function Read(arg1:string):Promise<imagemeta.ImageInfo>;
