// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Read(arg1) {
  return window['go']['imagemeta']['ImageMeta']['Read'](arg1);
}
