// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {archive} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function Create(arg1:archive.CreateRequest):Promise<string>;

export function Extract(arg1:archive.ExtractRequest):Promise<string>;

export function NewMount(arg1:string):Promise<string>;

export function ReleaseMount(arg1:string):Promise<void>;
