// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['archive']['Archive']['Cancel'](arg1);
}

export function Create(arg1) {
  return window['go']['archive']['Archive']['Create'](arg1);
}

export function Extract(arg1) {
  return window['go']['archive']['Archive']['Extract'](arg1);
}

export function NewMount(arg1) {
  return window['go']['archive']['Archive']['NewMount'](arg1);
}

export function ReleaseMount(arg1) {
  return window['go']['archive']['Archive']['ReleaseMount'](arg1);
}
