// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['search']['Search']['Cancel'](arg1);
}

export function Find(arg1) {
  return window['go']['search']['Search']['Find'](arg1);
}
