// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {search} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function Find(arg1:search.Criteria):Promise<string>;
