// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {textfile} from '../models';

export function ReadChunk(arg1:string,arg2:number,arg3:number,arg4:boolean):Promise<textfile.Chunk>;
