// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['hashing']['Hashing']['Cancel'](arg1);
}

export function Hash(arg1) {
  return window['go']['hashing']['Hashing']['Hash'](arg1);
}
