// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {hashing} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function Hash(arg1:hashing.Request):Promise<string>;
