// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {shell} from '../models';

export function ApplicationsFor(arg1:string):Promise<shell.Applications>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenWith(arg1:Array<string>,arg2:string):Promise<void>;

export function RevealInFinder(arg1:string):Promise<void>;
