// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFile(arg1:string):Promise<void>;

export function OpenWith(arg1:string,arg2:string):Promise<void>;

export function RevealInFinder(arg1:string):Promise<void>;
