// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFile(arg1) {
  return window['go']['shell']['Shell']['OpenFile'](arg1);
}

export function OpenWith(arg1, arg2) {
  return window['go']['shell']['Shell']['OpenWith'](arg1, arg2);
}

export function RevealInFinder(arg1) {
  return window['go']['shell']['Shell']['RevealInFinder'](arg1);
}
