// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Generate(arg1, arg2) {
  return window['go']['thumbs']['Thumbs']['Generate'](arg1, arg2);
}
