// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';

export function Exec(arg1:string,arg2:Array<any>):Promise<db.ExecResult>;

export function Path():Promise<string>;

export function Query(arg1:string,arg2:Array<any>):Promise<Array<Record<string, any>>>;

export function Tx(arg1:Array<db.Statement>):Promise<void>;
