// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {filesystem} from '../models';

export function Copy(arg1:Array<string>,arg2:string,arg3:string):Promise<filesystem.OpResult>;

export function CreateFile(arg1:string,arg2:string):Promise<filesystem.FileItem>;

export function CreateFolder(arg1:string,arg2:string):Promise<filesystem.FileItem>;

export function Delete(arg1:Array<string>):Promise<void>;

export function Exists(arg1:string):Promise<boolean>;

export function ListVolumes():Promise<Array<filesystem.Volume>>;

export function Move(arg1:Array<string>,arg2:string,arg3:string):Promise<filesystem.OpResult>;

export function ReadDirectory(arg1:string,arg2:boolean):Promise<Array<filesystem.FileItem>>;

export function ReadFileBase64(arg1:string,arg2:number):Promise<string>;

export function ReadFileInfo(arg1:string):Promise<filesystem.FileItem>;

export function ReadFileInfos(arg1:Array<string>):Promise<Array<filesystem.FileItem>>;

export function ReadTextFile(arg1:string,arg2:number):Promise<string>;

export function Rename(arg1:string,arg2:string):Promise<filesystem.FileItem>;

export function StandardPaths():Promise<filesystem.StandardPaths>;

export function Trash(arg1:Array<string>):Promise<Array<filesystem.TrashedItem>>;
