// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {filesystem} from '../models';

export function Exists(arg1:string):Promise<boolean>;

export function ListVolumes():Promise<Array<filesystem.Volume>>;

export function ReadDirectory(arg1:string,arg2:boolean):Promise<Array<filesystem.FileItem>>;

export function ReadFileInfo(arg1:string):Promise<filesystem.FileItem>;

export function StandardPaths():Promise<filesystem.StandardPaths>;
