// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Exists(arg1) {
  return window['go']['filesystem']['FS']['Exists'](arg1);
}

export function ListVolumes() {
  return window['go']['filesystem']['FS']['ListVolumes']();
}

export function ReadDirectory(arg1, arg2) {
  return window['go']['filesystem']['FS']['ReadDirectory'](arg1, arg2);
}

export function ReadFileInfo(arg1) {
  return window['go']['filesystem']['FS']['ReadFileInfo'](arg1);
}

export function StandardPaths() {
  return window['go']['filesystem']['FS']['StandardPaths']();
}
