// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Copy(arg1, arg2, arg3) {
  return window['go']['filesystem']['FS']['Copy'](arg1, arg2, arg3);
}

export function CreateFile(arg1, arg2, arg3, arg4) {
  return window['go']['filesystem']['FS']['CreateFile'](arg1, arg2, arg3, arg4);
}

export function CreateFolder(arg1, arg2) {
  return window['go']['filesystem']['FS']['CreateFolder'](arg1, arg2);
}

export function Delete(arg1) {
  return window['go']['filesystem']['FS']['Delete'](arg1);
}

export function Exists(arg1) {
  return window['go']['filesystem']['FS']['Exists'](arg1);
}

export function ListVolumes() {
  return window['go']['filesystem']['FS']['ListVolumes']();
}

export function Move(arg1, arg2, arg3) {
  return window['go']['filesystem']['FS']['Move'](arg1, arg2, arg3);
}

export function ReadDirectory(arg1, arg2) {
  return window['go']['filesystem']['FS']['ReadDirectory'](arg1, arg2);
}

export function ReadFileBase64(arg1, arg2) {
  return window['go']['filesystem']['FS']['ReadFileBase64'](arg1, arg2);
}

export function ReadFileInfo(arg1) {
  return window['go']['filesystem']['FS']['ReadFileInfo'](arg1);
}

export function ReadFileInfos(arg1) {
  return window['go']['filesystem']['FS']['ReadFileInfos'](arg1);
}

export function ReadTags(arg1) {
  return window['go']['filesystem']['FS']['ReadTags'](arg1);
}

export function ReadTextFile(arg1, arg2) {
  return window['go']['filesystem']['FS']['ReadTextFile'](arg1, arg2);
}

export function Rename(arg1, arg2) {
  return window['go']['filesystem']['FS']['Rename'](arg1, arg2);
}

export function SetTags(arg1, arg2) {
  return window['go']['filesystem']['FS']['SetTags'](arg1, arg2);
}

export function StandardPaths() {
  return window['go']['filesystem']['FS']['StandardPaths']();
}

export function Trash(arg1) {
  return window['go']['filesystem']['FS']['Trash'](arg1);
}
