// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Unwatch(arg1) {
  return window['go']['watcher']['Watcher']['Unwatch'](arg1);
}

export function Watch(arg1) {
  return window['go']['watcher']['Watcher']['Watch'](arg1);
}
